from .heading_task import HeadingTask
from .singlecombat_task import SingleCombatTask, HierarchicalSingleCombatTask
from .singlecombat_with_missle_task import SingleCombatDodgeMissileTask, HierarchicalSingleCombatDodgeMissileTask, HierarchicalSingleCombatShootTask, SingleCombatShootMissileTask
from .singlecombat_task_imitation import SingleCombatShootMissileImitationTask
from .singlecombat_task_back import SingleCombatShootMissileBackTask, HierarchicalSingleCombatShootMissileBackTask
from .singlecombat_task_guide import SingleCombatTaskGuide, HierarchicalSingleCombatTaskGuide
from .singlecombat_task_solo import HierarchicalSingleCombatShootMissileSoloTask
from .dodge_unknown_missle_task import HierarchicalSingleCombatDodgeUnknownMissileTask, HierarchicalSingleCombatDodgeKnownMissileTask
from .task_for_imitation import TaskForImitation